[package]
edition = "2021"
name = "littlefighter2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
heron = {git = "https://github.com/jcornaz/heron.git", features = ["2d", "debug-2d"]}
bevy-parallax = "0.1.0"
